[package]
name = "BEL-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.6"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
